FROM python:3.11-slim

WORKDIR /application

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

ENV API_KEY=[ENTER KEY]

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
